# テキスト解析設定
text_analysis:
  # 形態素解析設定
  morphological:
    mode: "C"  # Sudachiの分割モード（A: 短い, B: 中間, C: 長い）
    pos_filters:  # 抽出する品詞
      - "名詞"
      - "動詞"
      - "形容詞"
      - "副詞"
    normalize_text: true  # テキスト正規化を実行
    use_sudachi: true    # Sudachi形態素解析器を使用

  # キーワード抽出設定
  keyword:
    max_features: 1000   # 最大特徴数
    max_keywords: 20     # 抽出するキーワード数
    min_df: 2           # 最小文書頻度
    max_df: 0.95        # 最大文書頻度（比率）
    stop_words: "japanese"  # ストップワード
    use_idf: true       # IDF重み付けを使用
    
    # ハイブリッドアプローチの設定
    algorithm_weights:
      tfidf: 0.3       # TF-IDFの重み
      bert: 0.4        # BERTの重み
      textrank: 0.3    # TextRankの重み
    
    bert_model: "rinna/japanese-roberta-base"  # 文埋め込みモデル
    
    # TextRank設定
    textrank:
      window_size: 4   # 共起ウィンドウサイズ
      damping: 0.85    # ダンピング係数
      min_diff: 1e-5   # 収束閾値
      iterations: 30   # 最大反復回数

  # センチメント分析設定
  sentiment:
    model_name: "rinna/japanese-roberta-base"  # 基本モデル
    max_length: 512     # 最大トークン長
    batch_size: 16      # バッチサイズ
    threshold: 0.5      # 感情判定の閾値
    use_gpu: true       # GPU使用
    
    # 感情カテゴリ
    emotion_categories:
      - "喜び"
      - "悲しみ"
      - "怒り"
      - "恐れ"
      - "驚き"
      - "嫌悪"
    
    # 感情強度の重み
    intensity_weights:
      とても: 1.5
      かなり: 1.3
      やや: 0.7
      すこし: 0.5
      ほんの: 0.3
    
    # マルチモーダル設定
    multimodal:
      text_embedding_dim: 768
      audio_feature_dim: 128
      fusion_hidden_dim: 256
      attention_heads: 4
      dropout: 0.1
      use_attention: true

  # トピック分析設定
  topic:
    num_topics: 10      # トピック数
    update_every: 1     # 更新頻度
    passes: 20          # 学習パス数
    alpha: "auto"       # トピック分布のハイパーパラメータ
    eta: "auto"         # 単語分布のハイパーパラメータ
    min_prob: 0.01      # 最小確率閾値
    
    # コヒーレンス設定
    coherence:
      metric: "c_v"    # コヒーレンス指標
      topn: 20         # 評価する上位単語数
    
    # 辞書設定
    dictionary:
      no_below: 5      # 最小文書頻度
      no_above: 0.5    # 最大文書頻度（比率）
      keep_n: 100000   # 保持する語彙数

  # 分散処理設定
  distributed:
    ray:
      num_cpus: 4      # 使用CPU数
      num_gpus: 1      # 使用GPU数
      memory_limit: "8G"  # メモリ制限
    
    dask:
      n_workers: 4     # ワーカー数
      threads_per_worker: 2  # ワーカーあたりのスレッド数
      memory_limit: "2G"  # ワーカーあたりのメモリ制限

  # キャッシュ設定
  cache:
    max_size: 1000      # 最大キャッシュサイズ
    ttl: 3600          # キャッシュ有効期間（秒）
    cleanup_interval: 300  # クリーンアップ間隔（秒）
    
    # 分散キャッシュ設定
    distributed_cache:
      backend: "redis"  # キャッシュバックエンド
      host: "localhost"
      port: 6379
      db: 0
      password: null

# 音声処理設定
audio_processor:
  sample_rate: 16000
  max_duration: 30
  vad_mode: 3
  vad_frame_ms: 30
  min_speech_duration: 0.3

# Whisper設定
whisper:
  model_name: "large-v3"
  device: "cuda"
  compute_type: "float16"
  batch_size: 16
  language: "ja"
  beam_size: 5
  word_timestamps: true
  initial_prompt: "以下は日本語の音声を文字に起こしたものです。"
  
  use_onnx: true
  onnx_optimization:
    num_threads: 4
    optimization_level: 3

# システム設定
system:
  gpu_memory:
    max_memory: "8G"
    growth_rate: 0.7
    optimize_memory: true

  parallel:
    max_workers: 4
    chunk_size: 1000

# 出力設定
output:
  format: "json"
  save_intermediate: false
  timestamp_format: "%H:%M:%S.%f"
  include_word_timestamps: true

# モニタリング設定
monitoring:
  enabled: true
  metrics:
    - cpu_usage
    - gpu_usage
    - memory_usage
    - processing_time
    - transcription_accuracy
    - text_analysis_performance
    - sentiment_accuracy
    - topic_coherence
  log_interval: 60