# 音声認識システム設定

# 音声処理設定
audio_processor:
  sample_rate: 16000      # サンプリングレート（Hz）
  max_duration: 30        # 最大セグメント長（秒）
  vad_mode: 3            # VADの感度（0-3、3が最も感度が高い）
  vad_frame_ms: 30       # VADフレーム長（ms）
  min_speech_duration: 0.3  # 最小音声区間長（秒）

# Whisper設定
whisper:
  model_name: "large-v3"  # 最新のWhisperモデル
  device: "cuda"         # 実行デバイス（cuda or cpu）
  compute_type: "float16"  # 計算精度
  batch_size: 16         # バッチサイズ
  language: "ja"         # 言語設定（日本語）
  beam_size: 5          # ビームサーチのサイズ
  word_timestamps: true  # 単語レベルのタイムスタンプを有効化
  initial_prompt: "以下は日本語の音声を文字に起こしたものです。"  # 日本語用の初期プロンプト
  
  # ONNX最適化設定
  use_onnx: true        # ONNXランタイムを使用
  onnx_optimization:
    num_threads: 4      # 推論スレッド数
    optimization_level: 3  # 最適化レベル（0-3）

# 転写処理設定
transcription:
  confidence_threshold: 0.6   # 信頼度閾値
  min_segment_duration: 1.0   # 最小セグメント長（秒）
  max_merge_interval: 0.5     # 最大マージ間隔（秒）

# 入力層設定
input_layer:
  validation:
    max_file_size: 104857600  # 100MB
    allowed_formats:
      - wav
      - mp3
    max_duration: 3600  # 1時間
    min_sample_rate: 16000
    max_channels: 2
    
  storage:
    type: "minio"
    bucket: "audio-input"
    endpoint: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    
  queue:
    max_queue_size: 1000
    cleanup_interval: 3600  # 1時間
    retry_count: 3
    retry_delay: 5  # 秒

# システム設定
system:
  # GPUメモリ設定
  gpu_memory:
    max_memory: "8G"      # 最大メモリ使用量
    growth_rate: 0.7      # メモリ増加率
    optimize_memory: true  # メモリ最適化を有効化

  # 並列処理設定
  parallel:
    max_workers: 4        # 最大ワーカー数
    chunk_size: 1000      # チャンクサイズ

# キャッシュ設定
cache:
  enabled: true
  directory: "cache"
  max_size: "1G"
  ttl: 86400  # 24時間（秒）

# 出力設定
output:
  format: "json"          # 出力フォーマット（json/txt）
  save_intermediate: false  # 中間結果の保存
  timestamp_format: "%H:%M:%S.%f"  # タイムスタンプフォーマット
  include_word_timestamps: true  # 単語レベルのタイムスタンプを出力に含める

# エラーハンドリング設定
error_handling:
  max_retries: 3         # 最大リトライ回数
  retry_delay: 1.0       # リトライ間隔（秒）
  fallback_to_cpu: true  # GPU失敗時にCPUにフォールバック

# パフォーマンスモニタリング設定
monitoring:
  enabled: true
  metrics:
    - cpu_usage
    - gpu_usage
    - memory_usage
    - processing_time
    - transcription_accuracy
    - vad_performance
  log_interval: 60  # メトリクスログ間隔（秒）

# 日本語特化の設定
japanese:
  use_sudachi: true  # Sudachi形態素解析器を使用
  normalize_text: true  # テキスト正規化を実行
  fix_particles: true  # 助詞の修正を実行
  confidence_boost: 1.2  # 日本語認識時の信頼度ブースト